apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontback
  labels:
    app: frontback
spec:
  selector:
    matchLabels:
      app: frontback
      tier: frontback
  replicas: 1
  template:
    metadata:
      labels:
        app: frontback
        tier: frontback
    spec:
      containers:
        - image: frontend:1.1
          name: frontend
          ports:
            - containerPort: 80
        - image: ubuntu
          name: backend
          command: ["sleep", "500000"]

