apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontback
      tier: frontend
  template:
    metadata:
      labels:
        app: frontback
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:1.1
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: BACKEND_ADDRESS
          value: backend
        volumeMounts:
            - name: data
              mountPath: /mnt/nfs   
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: share
---
apiVersion: v1
kind: Service
metadata:
    name: frontend
spec:
    type: NodePort
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
        app: frontback
        tier: frontend

