all:
  hosts:
    master:
      ansible_host: 10.129.0.7
      ip: 10.129.0.7
      access_ip: 10.129.0.7
    node1:
      ansible_host: 10.129.0.25
      ip: 10.129.0.25
      access_ip: 10.129.0.25
    node2:
      ansible_host: 10.129.0.17
      ip: 10.129.0.17
      access_ip: 10.129.0.17
    node3:
      ansible_host: 10.129.0.10
      ip: 10.129.0.10
      access_ip: 10.129.0.10
    node4:
      ansible_host: 10.129.0.28
      ip: 10.129.0.28
      access_ip: 10.129.0.28
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        master:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}

